# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: simple-cli

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - # Build macOS, Linux and Windows versions
    main: ./simple.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -s -w

# .goreleaser.yml
brews:
  - # GitHub/GitLab repository to push the formula to
    tap:
      owner: philip kaim
      name: cli

    name: shedsuite-simple-cli

    homepage: https://github.com/PhilipKaim/simple-cli

    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: ""

    # Your app's description.
    # Default is empty.
    description: ""

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "MIT"

    # Packages your package depends on.
    dependencies:
      - name: git
      - name: go

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - "^*.md:"
